Adding command parser

diff --git a/updot b/updot
--- a/updot
+++ b/updot
@@ -19,7 +19,7 @@
 #//TODO parse command line options (--help --version)
 
 #-------------------------
-# Configuration variables
+# configuration variables
 #-------------------------
 updot_home="$HOME/.config/updot"
 updot_conf="$HOME/.config/updot/updot.conf"
@@ -27,19 +27,59 @@ repository_root=""
 declare -a dotfiles=( '.aliases .bash_profile .bashrc .gitconfig .i3/config .prompt .rtorrent.rc .vimrc 
                        .weechat/weechat.conf .xinitrc .Xresources .config/openbox/rc.xml' )
 
+#------------------
+# script variables
+#------------------
+version="0.0.1-indev"
+
 #------------
-# Exit codes
+# exit codes
 #------------
 no_repo=1
 no_dotfiles=2
+unknown_argument=3
+
+#-----------------
+# Parse arguments
+#-----------------
+parse_arguments() {
+  while :
+    do
+      case $1 in
+        -h | --help | -\?)
+          echo "Usage"
+          exit 0
+          ;;
+        -v | --version)
+          echo $version
+          exit 0
+          ;;
+        --)
+          echo "-- end"
+          shift
+          break
+          ;;
+        -*)
+          echo "WARN: Unknown option (ignored): $1" >&2
+          shift
+          exit $unknown_argument
+          ;;
+        *)
+          echo "no more options"
+          break
+          ;;
+      esac
+    done
+}
+
 
 #-----
-# Run
+# run
 #-----
 function run {
-  if [ ! -f $updot_conf ]; then
-    mkdir -p $updot_home
-    touch $updot_conf
+  if [[ ! -f "$updot_conf" ]]; then
+    mkdir -p "$updot_home"
+    touch "$updot_conf"
     write_to_conf "# updot configuration file"
     write_to_conf "  "
     write_to_conf "# Repository's root folder location"
@@ -56,7 +96,7 @@ function run {
     echo " -> Ensure that the config is tracking the dotfiles you want to track"
     echo "-----------------------------------------------------------------------"
   else
-    . $updot_conf
+    . "$updot_conf"
     update_dotfiles
   fi
 }
@@ -64,15 +104,15 @@ function run {
 
 
 #-----------------
-# File operations
+# file operations
 #-----------------
 function write_default_files {
   echo "==> Checking for commonly tracked dotfiles"
   write_to_conf_no_newline "dotfiles=('"
   for file in $dotfiles
     do
-      if [ -f $HOME/$file ]; then
-        write_to_conf_no_newline $file
+      if [[ -f "$HOME/$file" ]]; then
+        write_to_conf_no_newline "$file"
         echo "  -> $file found"
       fi
     done
@@ -80,20 +120,20 @@ function write_default_files {
 }
 
 write_to_conf() {
-  echo $1 >> $updot_conf
+  echo "$1" >> "$updot_conf"
 }
 
 write_to_conf_no_newline() {
-  echo -n "$1 " >> $updot_conf  
+  echo -n "$1 " >> "$updot_conf"
 }
 
 
 #-----------------
-# Update dotfiles
+# update dotfiles
 #-----------------
 function update_dotfiles {
 arrayLength=${#dotfiles[@]}
-if [ -z $repository_root ];then
+if [[ -z "$repository_root" ]];then
   echo "Please add your repository's root folder to your $updot_conf!"
   exit $no_repo
 elif [ $arrayLength -eq 0 ];then
@@ -104,9 +144,9 @@ else
   error=false
   for dotfile in $dotfiles
     do
-      if [ -f $HOME/$dotfile ];then
-        mkdir -p $repository_root/$(dirname $dotfile)
-        cp $HOME/$dotfile $repository_root/$(dirname $dotfile)
+      if [[ -f "$HOME/$dotfile" ]];then
+        mkdir -p "$repository_root/$(dirname $dotfile)"
+        cp "$HOME/$dotfile" "$repository_root/$(dirname $dotfile)"
         echo "  -> Updating $dotfile"
       else
         echo "  -> $dotfile not found!"
@@ -122,8 +162,9 @@ fi
 }
 
 #------
-# Exec
+# exec
 #------
-run
+#run
+parse_arguments $*
 
 # vim: set ft=sh :
